netToAxt Aal_noClass.net Aal.pre.chain Ath.genome.sm.fa.2bit Aal.genome.sm.fa.2bit stdout | axtSort stdin Ath_Aal.axt
netToAxt Aar_noClass.net Aar.pre.chain Ath.genome.sm.fa.2bit Aar.genome.sm.fa.2bit stdout | axtSort stdin Ath_Aar.axt
netToAxt Aly_noClass.net Aly.pre.chain Ath.genome.sm.fa.2bit Aly.genome.sm.fa.2bit stdout | axtSort stdin Ath_Aly.axt
netToAxt Ane_noClass.net Ane.pre.chain Ath.genome.sm.fa.2bit Ane.genome.sm.fa.2bit stdout | axtSort stdin Ath_Ane.axt
netToAxt Aru_noClass.net Aru.pre.chain Ath.genome.sm.fa.2bit Aru.genome.sm.fa.2bit stdout | axtSort stdin Ath_Aru.axt
netToAxt Bca_noClass.net Bca.pre.chain Ath.genome.sm.fa.2bit Bca.genome.sm.fa.2bit stdout | axtSort stdin Ath_Bca.axt
netToAxt Bju_noClass.net Bju.pre.chain Ath.genome.sm.fa.2bit Bju.genome.sm.fa.2bit stdout | axtSort stdin Ath_Bju.axt
netToAxt Bna_noClass.net Bna.pre.chain Ath.genome.sm.fa.2bit Bna.genome.sm.fa.2bit stdout | axtSort stdin Ath_Bna.axt
netToAxt Bni_noClass.net Bni.pre.chain Ath.genome.sm.fa.2bit Bni.genome.sm.fa.2bit stdout | axtSort stdin Ath_Bni.axt
netToAxt Bol_noClass.net Bol.pre.chain Ath.genome.sm.fa.2bit Bol.genome.sm.fa.2bit stdout | axtSort stdin Ath_Bol.axt
netToAxt Bra_noClass.net Bra.pre.chain Ath.genome.sm.fa.2bit Bra.genome.sm.fa.2bit stdout | axtSort stdin Ath_Bra.axt
netToAxt Cen_noClass.net Cen.pre.chain Ath.genome.sm.fa.2bit Cen.genome.sm.fa.2bit stdout | axtSort stdin Ath_Cen.axt
netToAxt Chi_noClass.net Chi.pre.chain Ath.genome.sm.fa.2bit Chi.genome.sm.fa.2bit stdout | axtSort stdin Ath_Chi.axt
netToAxt Cru_noClass.net Cru.pre.chain Ath.genome.sm.fa.2bit Cru.genome.sm.fa.2bit stdout | axtSort stdin Ath_Cru.axt
netToAxt Csa_noClass.net Csa.pre.chain Ath.genome.sm.fa.2bit Csa.genome.sm.fa.2bit stdout | axtSort stdin Ath_Csa.axt
netToAxt Dni_noClass.net Dni.pre.chain Ath.genome.sm.fa.2bit Dni.genome.sm.fa.2bit stdout | axtSort stdin Ath_Dni.axt
netToAxt Ech_noClass.net Ech.pre.chain Ath.genome.sm.fa.2bit Ech.genome.sm.fa.2bit stdout | axtSort stdin Ath_Ech.axt
netToAxt Iin_noClass.net Iin.pre.chain Ath.genome.sm.fa.2bit Iin.genome.sm.fa.2bit stdout | axtSort stdin Ath_Iin.axt
netToAxt Lma_noClass.net Lma.pre.chain Ath.genome.sm.fa.2bit Lma.genome.sm.fa.2bit stdout | axtSort stdin Ath_Lma.axt
netToAxt Mpy_noClass.net Mpy.pre.chain Ath.genome.sm.fa.2bit Mpy.genome.sm.fa.2bit stdout | axtSort stdin Ath_Mpy.axt
netToAxt Ovi_noClass.net Ovi.pre.chain Ath.genome.sm.fa.2bit Ovi.genome.sm.fa.2bit stdout | axtSort stdin Ath_Ovi.axt
netToAxt Raq_noClass.net Raq.pre.chain Ath.genome.sm.fa.2bit Raq.genome.sm.fa.2bit stdout | axtSort stdin Ath_Raq.axt
netToAxt Rbr_noClass.net Rbr.pre.chain Ath.genome.sm.fa.2bit Rbr.genome.sm.fa.2bit stdout | axtSort stdin Ath_Rbr.axt
netToAxt Rsa_noClass.net Rsa.pre.chain Ath.genome.sm.fa.2bit Rsa.genome.sm.fa.2bit stdout | axtSort stdin Ath_Rsa.axt
netToAxt Sal_noClass.net Sal.pre.chain Ath.genome.sm.fa.2bit Sal.genome.sm.fa.2bit stdout | axtSort stdin Ath_Sal.axt
netToAxt Sar_noClass.net Sar.pre.chain Ath.genome.sm.fa.2bit Sar.genome.sm.fa.2bit stdout | axtSort stdin Ath_Sar.axt
netToAxt Spa_noClass.net Spa.pre.chain Ath.genome.sm.fa.2bit Spa.genome.sm.fa.2bit stdout | axtSort stdin Ath_Spa.axt
netToAxt Tar_noClass.net Tar.pre.chain Ath.genome.sm.fa.2bit Tar.genome.sm.fa.2bit stdout | axtSort stdin Ath_Tar.axt
