axtToMaf Ath_Aal.axt Ath.genome.sm.fa.faSize Aal.genome.sm.fa.faSize Ath_Aal.maf -tPrefix=Ath. -qPrefix=Aal.
axtToMaf Ath_Aar.axt Ath.genome.sm.fa.faSize Aar.genome.sm.fa.faSize Ath_Aar.maf -tPrefix=Ath. -qPrefix=Aar.
axtToMaf Ath_Aly.axt Ath.genome.sm.fa.faSize Aly.genome.sm.fa.faSize Ath_Aly.maf -tPrefix=Ath. -qPrefix=Aly.
axtToMaf Ath_Ane.axt Ath.genome.sm.fa.faSize Ane.genome.sm.fa.faSize Ath_Ane.maf -tPrefix=Ath. -qPrefix=Ane.
axtToMaf Ath_Aru.axt Ath.genome.sm.fa.faSize Aru.genome.sm.fa.faSize Ath_Aru.maf -tPrefix=Ath. -qPrefix=Aru.
axtToMaf Ath_Bca.axt Ath.genome.sm.fa.faSize Bca.genome.sm.fa.faSize Ath_Bca.maf -tPrefix=Ath. -qPrefix=Bca.
axtToMaf Ath_Bju.axt Ath.genome.sm.fa.faSize Bju.genome.sm.fa.faSize Ath_Bju.maf -tPrefix=Ath. -qPrefix=Bju.
axtToMaf Ath_Bna.axt Ath.genome.sm.fa.faSize Bna.genome.sm.fa.faSize Ath_Bna.maf -tPrefix=Ath. -qPrefix=Bna.
axtToMaf Ath_Bni.axt Ath.genome.sm.fa.faSize Bni.genome.sm.fa.faSize Ath_Bni.maf -tPrefix=Ath. -qPrefix=Bni.
axtToMaf Ath_Bol.axt Ath.genome.sm.fa.faSize Bol.genome.sm.fa.faSize Ath_Bol.maf -tPrefix=Ath. -qPrefix=Bol.
axtToMaf Ath_Bra.axt Ath.genome.sm.fa.faSize Bra.genome.sm.fa.faSize Ath_Bra.maf -tPrefix=Ath. -qPrefix=Bra.
axtToMaf Ath_Cen.axt Ath.genome.sm.fa.faSize Cen.genome.sm.fa.faSize Ath_Cen.maf -tPrefix=Ath. -qPrefix=Cen.
axtToMaf Ath_Chi.axt Ath.genome.sm.fa.faSize Chi.genome.sm.fa.faSize Ath_Chi.maf -tPrefix=Ath. -qPrefix=Chi.
axtToMaf Ath_Cru.axt Ath.genome.sm.fa.faSize Cru.genome.sm.fa.faSize Ath_Cru.maf -tPrefix=Ath. -qPrefix=Cru.
axtToMaf Ath_Csa.axt Ath.genome.sm.fa.faSize Csa.genome.sm.fa.faSize Ath_Csa.maf -tPrefix=Ath. -qPrefix=Csa.
axtToMaf Ath_Dni.axt Ath.genome.sm.fa.faSize Dni.genome.sm.fa.faSize Ath_Dni.maf -tPrefix=Ath. -qPrefix=Dni.
axtToMaf Ath_Ech.axt Ath.genome.sm.fa.faSize Ech.genome.sm.fa.faSize Ath_Ech.maf -tPrefix=Ath. -qPrefix=Ech.
axtToMaf Ath_Iin.axt Ath.genome.sm.fa.faSize Iin.genome.sm.fa.faSize Ath_Iin.maf -tPrefix=Ath. -qPrefix=Iin.
axtToMaf Ath_Lma.axt Ath.genome.sm.fa.faSize Lma.genome.sm.fa.faSize Ath_Lma.maf -tPrefix=Ath. -qPrefix=Lma.
axtToMaf Ath_Mpy.axt Ath.genome.sm.fa.faSize Mpy.genome.sm.fa.faSize Ath_Mpy.maf -tPrefix=Ath. -qPrefix=Mpy.
axtToMaf Ath_Ovi.axt Ath.genome.sm.fa.faSize Ovi.genome.sm.fa.faSize Ath_Ovi.maf -tPrefix=Ath. -qPrefix=Ovi.
axtToMaf Ath_Raq.axt Ath.genome.sm.fa.faSize Raq.genome.sm.fa.faSize Ath_Raq.maf -tPrefix=Ath. -qPrefix=Raq.
axtToMaf Ath_Rbr.axt Ath.genome.sm.fa.faSize Rbr.genome.sm.fa.faSize Ath_Rbr.maf -tPrefix=Ath. -qPrefix=Rbr.
axtToMaf Ath_Rsa.axt Ath.genome.sm.fa.faSize Rsa.genome.sm.fa.faSize Ath_Rsa.maf -tPrefix=Ath. -qPrefix=Rsa.
axtToMaf Ath_Sal.axt Ath.genome.sm.fa.faSize Sal.genome.sm.fa.faSize Ath_Sal.maf -tPrefix=Ath. -qPrefix=Sal.
axtToMaf Ath_Sar.axt Ath.genome.sm.fa.faSize Sar.genome.sm.fa.faSize Ath_Sar.maf -tPrefix=Ath. -qPrefix=Sar.
axtToMaf Ath_Spa.axt Ath.genome.sm.fa.faSize Spa.genome.sm.fa.faSize Ath_Spa.maf -tPrefix=Ath. -qPrefix=Spa.
axtToMaf Ath_Tar.axt Ath.genome.sm.fa.faSize Tar.genome.sm.fa.faSize Ath_Tar.maf -tPrefix=Ath. -qPrefix=Tar.
