nohup axtChain axt/Aal_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Aal.genome.sm.fa.2bit chain/Aal_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Aar_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Aar.genome.sm.fa.2bit chain/Aar_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Aly_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Aly.genome.sm.fa.2bit chain/Aly_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Ane_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Ane.genome.sm.fa.2bit chain/Ane_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Aru_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Aru.genome.sm.fa.2bit chain/Aru_Chr5.chain -minScore=3000 -linearGap=medium &
## nohup axtChain axt/Asu_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Asu.genome.sm.fa.2bit chain/Asu_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Bca_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Bca.genome.sm.fa.2bit chain/Bca_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Bju_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Bju.genome.sm.fa.2bit chain/Bju_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Bna_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Bna.genome.sm.fa.2bit chain/Bna_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Bni_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Bni.genome.sm.fa.2bit chain/Bni_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Bol_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Bol.genome.sm.fa.2bit chain/Bol_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Bra_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Bra.genome.sm.fa.2bit chain/Bra_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Cen_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Cen.genome.sm.fa.2bit chain/Cen_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Chi_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Chi.genome.sm.fa.2bit chain/Chi_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Cru_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Cru.genome.sm.fa.2bit chain/Cru_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Csa_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Csa.genome.sm.fa.2bit chain/Csa_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Dni_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Dni.genome.sm.fa.2bit chain/Dni_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Ech_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Ech.genome.sm.fa.2bit chain/Ech_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Iin_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Iin.genome.sm.fa.2bit chain/Iin_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Lma_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Lma.genome.sm.fa.2bit chain/Lma_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Mpy_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Mpy.genome.sm.fa.2bit chain/Mpy_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Ovi_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Ovi.genome.sm.fa.2bit chain/Ovi_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Raq_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Raq.genome.sm.fa.2bit chain/Raq_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Rbr_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Rbr.genome.sm.fa.2bit chain/Rbr_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Rsa_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Rsa.genome.sm.fa.2bit chain/Rsa_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Sal_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Sal.genome.sm.fa.2bit chain/Sal_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Sar_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Sar.genome.sm.fa.2bit chain/Sar_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Spa_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Spa.genome.sm.fa.2bit chain/Spa_Chr5.chain -minScore=3000 -linearGap=medium &
nohup axtChain axt/Tar_Chr5.axt ../02.RepeatMasker/repeat_result_Ath/Ath.genome.sm.fa.2bit 2bit/Tar.genome.sm.fa.2bit chain/Tar_Chr5.chain -minScore=3000 -linearGap=medium &
