grep Ath new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Ath_gff.tmp
grep Aal new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Aal_gff.tmp
grep Aar new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Aar_gff.tmp
grep Aly new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Aly_gff.tmp
grep Ane new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Ane_gff.tmp
grep Aru new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Aru_gff.tmp
grep Bca new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Bca_gff.tmp
grep Bju new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Bju_gff.tmp
grep Bna new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Bna_gff.tmp
grep Bni new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Bni_gff.tmp
grep Bol new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Bol_gff.tmp
grep Bra new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Bra_gff.tmp
grep Cen new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Cen_gff.tmp
grep Chi new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Chi_gff.tmp
grep Cru new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Cru_gff.tmp
grep Csa new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Csa_gff.tmp
grep Dni new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Dni_gff.tmp
grep Ech new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Ech_gff.tmp
grep Iin new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Iin_gff.tmp
grep Lma new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Lma_gff.tmp
grep Mpy new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Mpy_gff.tmp
grep Ovi new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Ovi_gff.tmp
grep Raq new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Raq_gff.tmp
grep Rbr new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Rbr_gff.tmp
grep Rsa new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Rsa_gff.tmp
grep Sal new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Sal_gff.tmp
grep Sar new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Sar_gff.tmp
grep Spa new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Spa_gff.tmp
grep Tar new_ref_species_mulitway.table | sort -k3,3 -k5n > tmp/Tar_gff.tmp
