perl scripts/write_scaffold_lst_files.pl tmp/Aal_gff.tmp Aal &
perl scripts/write_scaffold_lst_files.pl tmp/Aar_gff.tmp Aar &
perl scripts/write_scaffold_lst_files.pl tmp/Aly_gff.tmp Aly &
perl scripts/write_scaffold_lst_files.pl tmp/Ane_gff.tmp Ane &
perl scripts/write_scaffold_lst_files.pl tmp/Aru_gff.tmp Aru &
perl scripts/write_scaffold_lst_files.pl tmp/Ath_gff.tmp Ath &
perl scripts/write_scaffold_lst_files.pl tmp/Bca_gff.tmp Bca &
perl scripts/write_scaffold_lst_files.pl tmp/Bju_gff.tmp Bju &
perl scripts/write_scaffold_lst_files.pl tmp/Bna_gff.tmp Bna &
perl scripts/write_scaffold_lst_files.pl tmp/Bni_gff.tmp Bni &
perl scripts/write_scaffold_lst_files.pl tmp/Bol_gff.tmp Bol &
perl scripts/write_scaffold_lst_files.pl tmp/Bra_gff.tmp Bra &
perl scripts/write_scaffold_lst_files.pl tmp/Cen_gff.tmp Cen &
perl scripts/write_scaffold_lst_files.pl tmp/Chi_gff.tmp Chi &
perl scripts/write_scaffold_lst_files.pl tmp/Cru_gff.tmp Cru &
perl scripts/write_scaffold_lst_files.pl tmp/Csa_gff.tmp Csa &
perl scripts/write_scaffold_lst_files.pl tmp/Dni_gff.tmp Dni &
perl scripts/write_scaffold_lst_files.pl tmp/Ech_gff.tmp Ech &
perl scripts/write_scaffold_lst_files.pl tmp/Iin_gff.tmp Iin &
perl scripts/write_scaffold_lst_files.pl tmp/Lma_gff.tmp Lma &
perl scripts/write_scaffold_lst_files.pl tmp/Mpy_gff.tmp Mpy &
perl scripts/write_scaffold_lst_files.pl tmp/Ovi_gff.tmp Ovi &
perl scripts/write_scaffold_lst_files.pl tmp/Raq_gff.tmp Raq &
perl scripts/write_scaffold_lst_files.pl tmp/Rbr_gff.tmp Rbr &
perl scripts/write_scaffold_lst_files.pl tmp/Rsa_gff.tmp Rsa &
perl scripts/write_scaffold_lst_files.pl tmp/Sal_gff.tmp Sal &
perl scripts/write_scaffold_lst_files.pl tmp/Sar_gff.tmp Sar &
perl scripts/write_scaffold_lst_files.pl tmp/Spa_gff.tmp Spa &
perl scripts/write_scaffold_lst_files.pl tmp/Tar_gff.tmp Tar &
