chainPreNet ../05.chainMergeSort/Aal.chain Ath.genome.sm.fa.faSize Aal.genome.sm.fa.faSize Aal.pre.chain &
chainPreNet ../05.chainMergeSort/Aar.chain Ath.genome.sm.fa.faSize Aar.genome.sm.fa.faSize Aar.pre.chain &
chainPreNet ../05.chainMergeSort/Aly.chain Ath.genome.sm.fa.faSize Aly.genome.sm.fa.faSize Aly.pre.chain &
chainPreNet ../05.chainMergeSort/Ane.chain Ath.genome.sm.fa.faSize Ane.genome.sm.fa.faSize Ane.pre.chain &
chainPreNet ../05.chainMergeSort/Aru.chain Ath.genome.sm.fa.faSize Aru.genome.sm.fa.faSize Aru.pre.chain &
# chainPreNet ../05.chainMergeSort/Asu.chain Ath.genome.sm.fa.faSize Asu.genome.sm.fa.faSize Asu.pre.chain &
chainPreNet ../05.chainMergeSort/Bca.chain Ath.genome.sm.fa.faSize Bca.genome.sm.fa.faSize Bca.pre.chain &
chainPreNet ../05.chainMergeSort/Bju.chain Ath.genome.sm.fa.faSize Bju.genome.sm.fa.faSize Bju.pre.chain &
chainPreNet ../05.chainMergeSort/Bna.chain Ath.genome.sm.fa.faSize Bna.genome.sm.fa.faSize Bna.pre.chain &
chainPreNet ../05.chainMergeSort/Bni.chain Ath.genome.sm.fa.faSize Bni.genome.sm.fa.faSize Bni.pre.chain &
chainPreNet ../05.chainMergeSort/Bol.chain Ath.genome.sm.fa.faSize Bol.genome.sm.fa.faSize Bol.pre.chain &
chainPreNet ../05.chainMergeSort/Bra.chain Ath.genome.sm.fa.faSize Bra.genome.sm.fa.faSize Bra.pre.chain &
chainPreNet ../05.chainMergeSort/Cen.chain Ath.genome.sm.fa.faSize Cen.genome.sm.fa.faSize Cen.pre.chain &
chainPreNet ../05.chainMergeSort/Chi.chain Ath.genome.sm.fa.faSize Chi.genome.sm.fa.faSize Chi.pre.chain &
chainPreNet ../05.chainMergeSort/Cru.chain Ath.genome.sm.fa.faSize Cru.genome.sm.fa.faSize Cru.pre.chain &
chainPreNet ../05.chainMergeSort/Csa.chain Ath.genome.sm.fa.faSize Csa.genome.sm.fa.faSize Csa.pre.chain &
chainPreNet ../05.chainMergeSort/Dni.chain Ath.genome.sm.fa.faSize Dni.genome.sm.fa.faSize Dni.pre.chain &
chainPreNet ../05.chainMergeSort/Ech.chain Ath.genome.sm.fa.faSize Ech.genome.sm.fa.faSize Ech.pre.chain &
chainPreNet ../05.chainMergeSort/Iin.chain Ath.genome.sm.fa.faSize Iin.genome.sm.fa.faSize Iin.pre.chain &
chainPreNet ../05.chainMergeSort/Lma.chain Ath.genome.sm.fa.faSize Lma.genome.sm.fa.faSize Lma.pre.chain &
chainPreNet ../05.chainMergeSort/Mpy.chain Ath.genome.sm.fa.faSize Mpy.genome.sm.fa.faSize Mpy.pre.chain &
chainPreNet ../05.chainMergeSort/Ovi.chain Ath.genome.sm.fa.faSize Ovi.genome.sm.fa.faSize Ovi.pre.chain &
chainPreNet ../05.chainMergeSort/Raq.chain Ath.genome.sm.fa.faSize Raq.genome.sm.fa.faSize Raq.pre.chain &
chainPreNet ../05.chainMergeSort/Rbr.chain Ath.genome.sm.fa.faSize Rbr.genome.sm.fa.faSize Rbr.pre.chain &
chainPreNet ../05.chainMergeSort/Rsa.chain Ath.genome.sm.fa.faSize Rsa.genome.sm.fa.faSize Rsa.pre.chain &
chainPreNet ../05.chainMergeSort/Sal.chain Ath.genome.sm.fa.faSize Sal.genome.sm.fa.faSize Sal.pre.chain &
chainPreNet ../05.chainMergeSort/Sar.chain Ath.genome.sm.fa.faSize Sar.genome.sm.fa.faSize Sar.pre.chain &
chainPreNet ../05.chainMergeSort/Spa.chain Ath.genome.sm.fa.faSize Spa.genome.sm.fa.faSize Spa.pre.chain &
chainPreNet ../05.chainMergeSort/Tar.chain Ath.genome.sm.fa.faSize Tar.genome.sm.fa.faSize Tar.pre.chain &
