chainMergeSort ../04.chain/chain/Aal*.chain > Aal.chain &
chainMergeSort ../04.chain/chain/Aar*.chain > Aar.chain &
chainMergeSort ../04.chain/chain/Aly*.chain > Aly.chain &
chainMergeSort ../04.chain/chain/Ane*.chain > Ane.chain &
chainMergeSort ../04.chain/chain/Aru*.chain > Aru.chain &
# chainMergeSort ../04.chain/chain/Asu*.chain > Asu.chain &
chainMergeSort ../04.chain/chain/Bca*.chain > Bca.chain &
chainMergeSort ../04.chain/chain/Bju*.chain > Bju.chain &
chainMergeSort ../04.chain/chain/Bna*.chain > Bna.chain &
chainMergeSort ../04.chain/chain/Bni*.chain > Bni.chain &
chainMergeSort ../04.chain/chain/Bol*.chain > Bol.chain &
chainMergeSort ../04.chain/chain/Bra*.chain > Bra.chain &
chainMergeSort ../04.chain/chain/Cen*.chain > Cen.chain &
chainMergeSort ../04.chain/chain/Chi*.chain > Chi.chain &
chainMergeSort ../04.chain/chain/Cru*.chain > Cru.chain &
chainMergeSort ../04.chain/chain/Csa*.chain > Csa.chain &
chainMergeSort ../04.chain/chain/Dni*.chain > Dni.chain &
chainMergeSort ../04.chain/chain/Ech*.chain > Ech.chain &
chainMergeSort ../04.chain/chain/Iin*.chain > Iin.chain &
chainMergeSort ../04.chain/chain/Lma*.chain > Lma.chain &
chainMergeSort ../04.chain/chain/Mpy*.chain > Mpy.chain &
chainMergeSort ../04.chain/chain/Ovi*.chain > Ovi.chain &
chainMergeSort ../04.chain/chain/Raq*.chain > Raq.chain &
chainMergeSort ../04.chain/chain/Rbr*.chain > Rbr.chain &
chainMergeSort ../04.chain/chain/Rsa*.chain > Rsa.chain &
chainMergeSort ../04.chain/chain/Sal*.chain > Sal.chain &
chainMergeSort ../04.chain/chain/Sar*.chain > Sar.chain &
chainMergeSort ../04.chain/chain/Spa*.chain > Spa.chain &
chainMergeSort ../04.chain/chain/Tar*.chain > Tar.chain &
