# export LD_LIBRARY_PATH=/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:$LD_LIBRARY_PATH

/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Aal -c Aal_1 -o results/Aal &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Aar -c Aar_1 -o results/Aar &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Aly -c Aly_1 -o results/Aly &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Ane -c Ane_1 -o results/Ane &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Aru -c Aru_1 -o results/Aru &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Asu -c Asu_1 -o results/Asu &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Ath -c Ath_1 -o results/Ath &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Bca -c Bca_1 -o results/Bca &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Bju -c Bju_1 -o results/Bju &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Bna -c Bna_1 -o results/Bna &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Bni -c Bni_1 -o results/Bni &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Bol -c Bol_1 -o results/Bol &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Bra -c Bra_1 -o results/Bra &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Cen -c Cen_1 -o results/Cen &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Cgy -c Cgy_1 -o results/Cgy &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Chi -c Chi_1 -o results/Chi &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Cpa -c Cpa_1 -o results/Cpa &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Cru -c Cru_1 -o results/Cru &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Csa -c Csa_1 -o results/Csa &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Csp -c Csp_1 -o results/Csp &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Dni -c Dni_1 -o results/Dni &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Ech -c Ech_1 -o results/Ech &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Iin -c Iin_1 -o results/Iin &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Lma -c Lma_1 -o results/Lma &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Mpy -c Mpy_1 -o results/Mpy &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Ovi -c Ovi_1 -o results/Ovi &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Raq -c Raq_1 -o results/Raq &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Rbr -c Rbr_1 -o results/Rbr &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Rsa -c Rsa_1 -o results/Rsa &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Sal -c Sal_1 -o results/Sal &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Sar -c Sar_1 -o results/Sar &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Spa -c Spa_1 -o results/Spa &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Tar -c Tar_1 -o results/Tar &
/data01/masterHome/lchunjin//00.Software/13.DupGen_finder/DupGen_finder/DupGen_finder-unique.pl -i data -t Tha -c Tha_1 -o results/Tha &
