RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Aar.genome.fa -dir repeat_result_Aar 1>Aar_log.o.txt 2>Aar_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Aly.genome.fa -dir repeat_result_Aly 1>Aly_log.o.txt 2>Aly_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Asu.genome.fa -dir repeat_result_Asu 1>Asu_log.o.txt 2>Asu_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Aru.genome.fa -dir repeat_result_Aru 1>Aru_log.o.txt 2>Aru_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Bni.genome.fa -dir repeat_result_Bni 1>Bni_log.o.txt 2>Bni_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Cru.genome.fa -dir repeat_result_Cru 1>Cru_log.o.txt 2>Cru_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Dni.genome.fa -dir repeat_result_Dni 1>Dni_log.o.txt 2>Dni_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Ech.genome.fa -dir repeat_result_Ech 1>Ech_log.o.txt 2>Ech_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Lma.genome.fa -dir repeat_result_Lma 1>Lma_log.o.txt 2>Lma_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Mde.genome.fa -dir repeat_result_Mde 1>Mde_log.o.txt 2>Mde_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Mpy.genome.fa -dir repeat_result_Mpy 1>Mpy_log.o.txt 2>Mpy_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Raq.genome.fa -dir repeat_result_Raq 1>Raq_log.o.txt 2>Raq_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Rbr.genome.fa -dir repeat_result_Rbr 1>Rbr_log.o.txt 2>Rbr_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Sal.genome.fa -dir repeat_result_Sal 1>Sal_log.o.txt 2>Sal_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Sar.genome.fa -dir repeat_result_Sar 1>Sar_log.o.txt 2>Sar_log.e.txt &
RepeatMasker -pa 12 -species Brassicaceae -e rmblast -xsmall -html -s -gff Tar.genome.fa -dir repeat_result_Tar 1>Tar_log.o.txt 2>Tar_log.e.txt &
